"""Export the PostgreSQL schema (DDL) from the SQLAlchemy models to database/schema.sql.

    python -m database.export_schema
"""
from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from backend.app import models  # noqa: F401  (registers tables)
from backend.app.database import Base
from backend.app.services.audit import IMMUTABLE_SQL


def main():
    out = ["-- MPLADS Risk Intelligence Platform - PostgreSQL schema (generated by database/export_schema.py)",
           "-- The application creates these tables automatically at startup; this file is for reference / manual setup.\n"]
    for table in Base.metadata.sorted_tables:
        out.append(str(CreateTable(table).compile(dialect=postgresql.dialect())).strip() + ";\n")
        for idx in table.indexes:
            out.append(str(CreateIndex(idx).compile(dialect=postgresql.dialect())).strip() + ";")
        out.append("")
    out.append("-- Audit trail is append-only: UPDATE / DELETE / TRUNCATE are rejected by triggers")
    out.append(IMMUTABLE_SQL.strip())
    path = Path(__file__).with_name("schema.sql")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("Wrote", path)


if __name__ == "__main__":
    main()
