-- MPLADS Risk Intelligence Platform - PostgreSQL schema (generated by database/export_schema.py)
-- The application creates these tables automatically at startup; this file is for reference / manual setup.

CREATE TABLE agencies (
	agency_id SERIAL NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	district VARCHAR(80), 
	constituency VARCHAR(80), 
	total_projects INTEGER NOT NULL, 
	completed_projects INTEGER NOT NULL, 
	delayed_projects INTEGER NOT NULL, 
	average_delay FLOAT NOT NULL, 
	complaints INTEGER NOT NULL, 
	inspections INTEGER NOT NULL, 
	previous_high_risk_cases INTEGER NOT NULL, 
	historical_performance FLOAT NOT NULL, 
	PRIMARY KEY (agency_id), 
	UNIQUE (name)
);


CREATE TABLE audit_logs (
	audit_id BIGSERIAL NOT NULL, 
	user_id INTEGER, 
	user_name VARCHAR(120), 
	role VARCHAR(40), 
	action VARCHAR(60) NOT NULL, 
	entity_type VARCHAR(40), 
	entity_id VARCHAR(60), 
	project_id INTEGER, 
	previous_value JSONB, 
	new_value JSONB, 
	reason TEXT, 
	timestamp TIMESTAMP WITH TIME ZONE NOT NULL, 
	ip_address VARCHAR(64), 
	prev_hash VARCHAR(64), 
	record_hash VARCHAR(64), 
	PRIMARY KEY (audit_id)
);

CREATE INDEX ix_audit_logs_project_id ON audit_logs (project_id);
CREATE INDEX ix_audit_logs_timestamp ON audit_logs (timestamp);
CREATE INDEX ix_audit_logs_action ON audit_logs (action);

CREATE TABLE revoked_tokens (
	jti VARCHAR(64) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (jti)
);


CREATE TABLE roles_permissions (
	role_id SERIAL NOT NULL, 
	role_name VARCHAR(40) NOT NULL, 
	permission VARCHAR(80) NOT NULL, 
	description VARCHAR(255), 
	PRIMARY KEY (role_id), 
	UNIQUE (role_name, permission)
);

CREATE INDEX ix_roles_permissions_role_name ON roles_permissions (role_name);

CREATE TABLE users (
	user_id SERIAL NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	role VARCHAR(40) NOT NULL, 
	agency_id INTEGER, 
	department VARCHAR(120), 
	district VARCHAR(80), 
	constituency VARCHAR(80), 
	is_inspector BOOLEAN NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	last_login TIMESTAMP WITH TIME ZONE, 
	failed_attempts INTEGER NOT NULL, 
	locked_until TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (user_id), 
	FOREIGN KEY(agency_id) REFERENCES agencies (agency_id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE INDEX ix_users_role ON users (role);

CREATE TABLE projects (
	project_id SERIAL NOT NULL, 
	project_code VARCHAR(40) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	category VARCHAR(60) NOT NULL, 
	location VARCHAR(200), 
	latitude FLOAT, 
	longitude FLOAT, 
	district VARCHAR(80), 
	constituency VARCHAR(80), 
	agency_id INTEGER, 
	description TEXT, 
	sanction_date DATE, 
	sanctioned_amount NUMERIC(14, 2) NOT NULL, 
	released_amount NUMERIC(14, 2) NOT NULL, 
	expenditure NUMERIC(14, 2) NOT NULL, 
	remaining_amount NUMERIC(14, 2) NOT NULL, 
	progress FLOAT NOT NULL, 
	planned_progress FLOAT, 
	start_date DATE, 
	deadline DATE, 
	revised_deadline DATE, 
	completion_date DATE, 
	as_of_date DATE, 
	reporting_period VARCHAR(80), 
	delay_days INTEGER NOT NULL, 
	budget_revisions INTEGER NOT NULL, 
	extension_requests INTEGER NOT NULL, 
	milestones JSONB, 
	status VARCHAR(60) NOT NULL, 
	verification_status VARCHAR(30) NOT NULL, 
	is_public BOOLEAN NOT NULL, 
	is_historical BOOLEAN NOT NULL, 
	case_level INTEGER NOT NULL, 
	created_by INTEGER, 
	verified_by INTEGER, 
	verified_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (project_id), 
	FOREIGN KEY(agency_id) REFERENCES agencies (agency_id), 
	FOREIGN KEY(created_by) REFERENCES users (user_id), 
	FOREIGN KEY(verified_by) REFERENCES users (user_id)
);

CREATE INDEX ix_projects_category ON projects (category);
CREATE INDEX ix_projects_cat_dist ON projects (category, district);
CREATE INDEX ix_projects_status ON projects (status);
CREATE UNIQUE INDEX ix_projects_project_code ON projects (project_code);
CREATE INDEX ix_projects_district ON projects (district);
CREATE INDEX ix_projects_agency_id ON projects (agency_id);

CREATE TABLE agency_requests (
	request_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	agency_id INTEGER NOT NULL, 
	request_type VARCHAR(30) NOT NULL, 
	requested_deadline DATE, 
	requested_amount NUMERIC(14, 2), 
	justification TEXT NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	submitted_by INTEGER, 
	decided_by INTEGER, 
	decision_note TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (request_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE, 
	FOREIGN KEY(agency_id) REFERENCES agencies (agency_id), 
	FOREIGN KEY(submitted_by) REFERENCES users (user_id), 
	FOREIGN KEY(decided_by) REFERENCES users (user_id)
);

CREATE INDEX ix_agency_requests_project_id ON agency_requests (project_id);
CREATE INDEX ix_agency_requests_status ON agency_requests (status);

CREATE TABLE clarifications (
	clarification_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	agency_id INTEGER NOT NULL, 
	requested_by INTEGER NOT NULL, 
	question TEXT NOT NULL, 
	response TEXT, 
	responded_by INTEGER, 
	status VARCHAR(20) NOT NULL, 
	due_date DATE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	responded_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (clarification_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE, 
	FOREIGN KEY(agency_id) REFERENCES agencies (agency_id), 
	FOREIGN KEY(requested_by) REFERENCES users (user_id), 
	FOREIGN KEY(responded_by) REFERENCES users (user_id)
);

CREATE INDEX ix_clarifications_status ON clarifications (status);
CREATE INDEX ix_clarifications_project_id ON clarifications (project_id);

CREATE TABLE complaints (
	complaint_id SERIAL NOT NULL, 
	tracking_id VARCHAR(24) NOT NULL, 
	project_id INTEGER, 
	project_code_ref VARCHAR(40), 
	citizen_id INTEGER NOT NULL, 
	category VARCHAR(60) NOT NULL, 
	description TEXT NOT NULL, 
	incident_date DATE, 
	location_text VARCHAR(255), 
	evidence JSONB, 
	anonymous BOOLEAN NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	serious BOOLEAN NOT NULL, 
	screening_status VARCHAR(20) NOT NULL, 
	screened_by INTEGER, 
	screened_at TIMESTAMP WITH TIME ZONE, 
	screening_note TEXT, 
	response TEXT, 
	responded_by INTEGER, 
	responded_at TIMESTAMP WITH TIME ZONE, 
	resolution TEXT, 
	resolved_by INTEGER, 
	resolved_at TIMESTAMP WITH TIME ZONE, 
	feedback_satisfied BOOLEAN, 
	feedback_rating INTEGER, 
	feedback_comment TEXT, 
	appeal TEXT, 
	appeal_status VARCHAR(20) NOT NULL, 
	appeal_decision_note TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (complaint_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id), 
	FOREIGN KEY(citizen_id) REFERENCES users (user_id), 
	FOREIGN KEY(screened_by) REFERENCES users (user_id), 
	FOREIGN KEY(responded_by) REFERENCES users (user_id), 
	FOREIGN KEY(resolved_by) REFERENCES users (user_id)
);

CREATE INDEX ix_complaints_project_code_ref ON complaints (project_code_ref);
CREATE UNIQUE INDEX ix_complaints_tracking_id ON complaints (tracking_id);
CREATE INDEX ix_complaints_project_id ON complaints (project_id);
CREATE INDEX ix_complaints_status ON complaints (status);

CREATE TABLE inspections (
	inspection_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	requested_by INTEGER NOT NULL, 
	assigned_to INTEGER, 
	assigned_by INTEGER, 
	reason TEXT NOT NULL, 
	priority VARCHAR(20) NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	scheduled_date DATE, 
	due_date DATE, 
	findings TEXT, 
	recommendation TEXT, 
	outcome VARCHAR(60), 
	evidence JSONB, 
	requested_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	closed_at TIMESTAMP WITH TIME ZONE, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (inspection_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE, 
	FOREIGN KEY(requested_by) REFERENCES users (user_id), 
	FOREIGN KEY(assigned_to) REFERENCES users (user_id), 
	FOREIGN KEY(assigned_by) REFERENCES users (user_id)
);

CREATE INDEX ix_inspections_status ON inspections (status);
CREATE INDEX ix_inspections_project_id ON inspections (project_id);

CREATE TABLE notifications (
	notification_id SERIAL NOT NULL, 
	recipient_id INTEGER NOT NULL, 
	type VARCHAR(50) NOT NULL, 
	message TEXT NOT NULL, 
	priority VARCHAR(10) NOT NULL, 
	status VARCHAR(10) NOT NULL, 
	project_id INTEGER, 
	entity_type VARCHAR(40), 
	entity_id VARCHAR(40), 
	dedupe_key VARCHAR(120), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	read_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (notification_id), 
	FOREIGN KEY(recipient_id) REFERENCES users (user_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id)
);

CREATE INDEX ix_notif_recipient_status ON notifications (recipient_id, status);
CREATE INDEX ix_notifications_dedupe_key ON notifications (dedupe_key);
CREATE INDEX ix_notifications_created_at ON notifications (created_at);

CREATE TABLE payments (
	payment_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	paid_on DATE, 
	amount NUMERIC(14, 2) NOT NULL, 
	description VARCHAR(255), 
	reference VARCHAR(80), 
	PRIMARY KEY (payment_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE
);

CREATE INDEX ix_payments_project_id ON payments (project_id);

CREATE TABLE progress_reports (
	report_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	agency_id INTEGER, 
	submitted_by INTEGER, 
	period_label VARCHAR(80), 
	report_date DATE NOT NULL, 
	progress FLOAT NOT NULL, 
	planned_progress FLOAT, 
	expenditure NUMERIC(14, 2) NOT NULL, 
	delay_explanation TEXT, 
	notes TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (report_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE, 
	FOREIGN KEY(agency_id) REFERENCES agencies (agency_id), 
	FOREIGN KEY(submitted_by) REFERENCES users (user_id)
);

CREATE INDEX ix_progress_reports_project_id ON progress_reports (project_id);

CREATE TABLE reviews (
	review_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	citizen_id INTEGER NOT NULL, 
	rating INTEGER NOT NULL, 
	comment TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (review_id), 
	UNIQUE (project_id, citizen_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE, 
	FOREIGN KEY(citizen_id) REFERENCES users (user_id)
);

CREATE INDEX ix_reviews_project_id ON reviews (project_id);

CREATE TABLE risk_analysis (
	risk_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	risk_score FLOAT NOT NULL, 
	risk_level VARCHAR(20) NOT NULL, 
	contributing_factors JSONB NOT NULL, 
	historical_comparison JSONB NOT NULL, 
	anomaly_score FLOAT, 
	rule_score FLOAT, 
	model_version VARCHAR(60) NOT NULL, 
	input_snapshot JSONB, 
	analyzed_by INTEGER, 
	timestamp TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (risk_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE, 
	FOREIGN KEY(analyzed_by) REFERENCES users (user_id)
);

CREATE INDEX ix_risk_analysis_project_id ON risk_analysis (project_id);
CREATE INDEX ix_risk_analysis_timestamp ON risk_analysis (timestamp);

CREATE TABLE decisions (
	decision_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	role VARCHAR(40) NOT NULL, 
	decision VARCHAR(60) NOT NULL, 
	reason TEXT NOT NULL, 
	evidence_reviewed JSONB, 
	follow_up_date DATE, 
	action TEXT, 
	risk_id INTEGER, 
	previous_status VARCHAR(60), 
	new_status VARCHAR(60), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (decision_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (user_id), 
	FOREIGN KEY(risk_id) REFERENCES risk_analysis (risk_id)
);

CREATE INDEX ix_decisions_project_id ON decisions (project_id);
CREATE INDEX ix_decisions_created_at ON decisions (created_at);

CREATE TABLE documents (
	document_id SERIAL NOT NULL, 
	project_id INTEGER, 
	complaint_id INTEGER, 
	inspection_id INTEGER, 
	document_type VARCHAR(50) NOT NULL, 
	file_name VARCHAR(255) NOT NULL, 
	file_path VARCHAR(500) NOT NULL, 
	content_type VARCHAR(100), 
	size_bytes INTEGER, 
	sha256 VARCHAR(64), 
	version INTEGER NOT NULL, 
	is_public BOOLEAN NOT NULL, 
	description VARCHAR(255), 
	uploaded_by INTEGER, 
	uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (document_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id), 
	FOREIGN KEY(complaint_id) REFERENCES complaints (complaint_id), 
	FOREIGN KEY(inspection_id) REFERENCES inspections (inspection_id), 
	FOREIGN KEY(uploaded_by) REFERENCES users (user_id)
);

CREATE INDEX ix_documents_project_id ON documents (project_id);

CREATE TABLE extractions (
	extraction_id SERIAL NOT NULL, 
	document_id INTEGER, 
	uploaded_by INTEGER NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	fields JSONB NOT NULL, 
	payments JSONB NOT NULL, 
	milestones JSONB NOT NULL, 
	validation JSONB, 
	notes JSONB, 
	project_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	verified_by INTEGER, 
	verified_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (extraction_id), 
	FOREIGN KEY(document_id) REFERENCES documents (document_id), 
	FOREIGN KEY(uploaded_by) REFERENCES users (user_id), 
	FOREIGN KEY(project_id) REFERENCES projects (project_id), 
	FOREIGN KEY(verified_by) REFERENCES users (user_id)
);

CREATE INDEX ix_extractions_status ON extractions (status);

-- Audit trail is append-only: UPDATE / DELETE / TRUNCATE are rejected by triggers
CREATE OR REPLACE FUNCTION audit_logs_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only';
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_audit_logs_immutable ON audit_logs;
CREATE TRIGGER trg_audit_logs_immutable BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable();
DROP TRIGGER IF EXISTS trg_audit_logs_truncate ON audit_logs;
CREATE TRIGGER trg_audit_logs_truncate BEFORE TRUNCATE ON audit_logs
    FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_immutable();
